- added option --enable-lock[=lockfile|fcntl|no]i to configure.ac.   Default is to search for liblockfile or fcntl, in this order, and use   the first found or abort if none available. No locking is only used if   explicitly set; - fixed an old bug in osbf_lock_fcntl that prevented retries when trying   to lock a file; - removed abs() for sorting confidences; - removed derived files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1484,7 +1484,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-osbf-name=NAME   set the module name (default = osbf3)
+  --enable-osbf-name=[NAME]
+                          set the module name - default=osbf3
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-static[=PKGS]  build static libraries [default=no]
@@ -1492,12 +1493,18 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --enable-osbf-site-install   by default the lua module is installed
-                          under $prefix/lib/lua/$lua_version. If you set this
+  --enable-osbf-site-install
+                          by default the lua module is installed under
+                          $prefix/lib/lua/$lua_version. If you set this
                           option, the lua modules will be installed wherever
-                          your Lua setup thinks it is best.
-                          WARNING: if you set this option, existing osbf
-                                   modules, if any, may be overwritten.
+                          your Lua setup thinks it is best. WARNING: if you
+                          set this option, existing osbf modules, if any, may
+                          be overwritten.
+  --enable-lock[=lockfile|fcntl|no]
+                          default is to search for liblockfile or fcntl, in
+                          this order, and use the first found or abort if none
+                          is available. You can force one of them or disable
+                          locking.
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -2416,12 +2423,12 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
 
-#MOD_NAME=osbf3
+MOD_NAME=osbf3
 # Check whether --enable-osbf-name was given.
 if test "${enable_osbf_name+set}" = set; then
   enableval=$enable_osbf_name; MOD_NAME=$enableval
 else
-  MOD_NAME=osbf3
+  MOD_NAME=$MOD_NAME
 fi
 
 
@@ -5510,7 +5517,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5513 "configure"' > conftest.$ac_ext
+  echo '#line 5520 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8022,11 +8029,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8025: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8032: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8029: \$? = $ac_status" >&5
+   echo "$as_me:8036: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8312,11 +8319,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8322: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8319: \$? = $ac_status" >&5
+   echo "$as_me:8326: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8416,11 +8423,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8419: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8423: \$? = $ac_status" >&5
+   echo "$as_me:8430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10783,7 +10790,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10786 "configure"
+#line 10793 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10883,7 +10890,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10886 "configure"
+#line 10893 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13307,11 +13314,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13310: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13317: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13314: \$? = $ac_status" >&5
+   echo "$as_me:13321: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13411,11 +13418,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13414: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13421: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13418: \$? = $ac_status" >&5
+   echo "$as_me:13425: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14988,11 +14995,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14991: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14998: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14995: \$? = $ac_status" >&5
+   echo "$as_me:15002: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -15092,11 +15099,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15095: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15102: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15099: \$? = $ac_status" >&5
+   echo "$as_me:15106: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17301,11 +17308,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17304: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17311: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17308: \$? = $ac_status" >&5
+   echo "$as_me:17315: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17591,11 +17598,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17594: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17601: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17598: \$? = $ac_status" >&5
+   echo "$as_me:17605: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17695,11 +17702,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17698: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17705: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17702: \$? = $ac_status" >&5
+   echo "$as_me:17709: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20855,14 +20862,14 @@ _ACEOF
 
 fi
 
+#AC_CHECK_HEADERS([fcntl.h float.h inttypes.h stddef.h stdlib.h string.h unistd.h])
 
 
 
 
 
 
-
-for ac_header in fcntl.h float.h inttypes.h stddef.h stdlib.h string.h unistd.h
+for ac_header in float.h inttypes.h stddef.h stdlib.h string.h unistd.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
@@ -24500,10 +24507,183 @@ else
 fi
 
 
-        no_lock=1
-    lockfile=2
-    fcntl_lock=3
-    if test "${ac_cv_header_lockfile_h+set}" = set; then
+        # Check whether --enable-lock was given.
+if test "${enable_lock+set}" = set; then
+  enableval=$enable_lock;
+else
+        enable_lock=yes
+fi
+
+
+    no_lock=1; lockfile=2; fcntl_lock=3
+    if test "$enable_lock" = "lockfile"; then
+  { echo "$as_me:$LINENO: checking for lockfile_create in -lliblockfile" >&5
+echo $ECHO_N "checking for lockfile_create in -lliblockfile... $ECHO_C" >&6; }
+if test "${ac_cv_lib_liblockfile_lockfile_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lliblockfile  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char lockfile_create ();
+int
+main ()
+{
+return lockfile_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_liblockfile_lockfile_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_liblockfile_lockfile_create=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_liblockfile_lockfile_create" >&5
+echo "${ECHO_T}$ac_cv_lib_liblockfile_lockfile_create" >&6; }
+if test $ac_cv_lib_liblockfile_lockfile_create = yes; then
+  lock_method=$lockfile; lock_method_name=liblockfile
+else
+  { { echo "$as_me:$LINENO: error: --enable-lock=lockfile was given, but test for liblockfile failed
+See \`config.log' for more details." >&5
+echo "$as_me: error: --enable-lock=lockfile was given, but test for liblockfile failed
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+elif test "$enable_lock" = "fcntl"; then
+  { echo "$as_me:$LINENO: checking for fcntl" >&5
+echo $ECHO_N "checking for fcntl... $ECHO_C" >&6; }
+if test "${ac_cv_func_fcntl+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define fcntl to an innocuous variant, in case <limits.h> declares fcntl.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define fcntl innocuous_fcntl
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char fcntl (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef fcntl
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char fcntl ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_fcntl || defined __stub___fcntl
+choke me
+#endif
+
+int
+main ()
+{
+return fcntl ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_fcntl=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_fcntl=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_fcntl" >&5
+echo "${ECHO_T}$ac_cv_func_fcntl" >&6; }
+if test $ac_cv_func_fcntl = yes; then
+  lock_method=$fcntl_lock; lock_method_name=fcntl
+else
+  { { echo "$as_me:$LINENO: error: --enable-lock=fcntl was given, but test for fcntl failed
+See \`config.log' for more details." >&5
+echo "$as_me: error: --enable-lock=fcntl was given, but test for fcntl failed
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+elif test "$enable_lock" = "no"; then
+  lock_method=$no_lock; lock_method_name=none
+elif test "$enable_lock" = "yes"; then
+  if test "${ac_cv_header_lockfile_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for lockfile.h" >&5
 echo $ECHO_N "checking for lockfile.h... $ECHO_C" >&6; }
 if test "${ac_cv_header_lockfile_h+set}" = set; then
@@ -24629,7 +24809,7 @@ echo "${ECHO_T}$ac_cv_header_lockfile_h" >&6; }
 
 fi
 if test $ac_cv_header_lockfile_h = yes; then
-  lock_method=$lockfile
+  lock_method=$lockfile; lock_method_name=liblockfile
 else
   if test "${ac_cv_header_fcntl_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for fcntl.h" >&5
@@ -24757,16 +24937,26 @@ echo "${ECHO_T}$ac_cv_header_fcntl_h" >&6; }
 
 fi
 if test $ac_cv_header_fcntl_h = yes; then
-  lock_method=$fcntl_lock
+  lock_method=$fcntl_lock; lock_method_name=fcntl
 else
-  lock_method=$no_lock;
-         { echo "$as_me:$LINENO: WARNING: Neither lockfile.h nor fnctl.h found!" >&5
-echo "$as_me: WARNING: Neither lockfile.h nor fnctl.h found!" >&2;}
+  { { echo "$as_me:$LINENO: error: Neither lockfile.h nor fnctl.h found!
+See \`config.log' for more details." >&5
+echo "$as_me: error: Neither lockfile.h nor fnctl.h found!
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
 fi
 
+
+else
+  { { echo "$as_me:$LINENO: error: Invalid lock method: \"$enable_lock\"
+See \`config.log' for more details." >&5
+echo "$as_me: error: Invalid lock method: \"$enable_lock\"
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
     LUA_DEFINES="-DLUA$lua_vndot -D$LUA_HAVE_COMPAT51 -DLOCK_METHOD=$lock_method"
@@ -26363,8 +26553,10 @@ fi
 
 echo
 echo "--------------------------------------------------------"
-echo " Lua Binary:          $LUA"
-echo " Lua Version:         $lua_version"
+echo " Module name:         $MOD_NAME"
+echo " Lock method:         $lock_method_name"
+echo " Lua binary:          $LUA"
+echo " Lua version:         $lua_version"
 echo " Lua C-modules dir:   $LUA_INSTALL_CMOD"
 echo "--------------------------------------------------------"
 
