changes (forgot to push)

diff --git a/handbuild/configure b/handbuild/configure
--- a/handbuild/configure
+++ b/handbuild/configure
@@ -60,6 +60,7 @@ LOG="configure.log"
 echo "DATE='`date`'" > $LOG
 
 function fail {
+  echo
   echo "$*" | tee -a $LOG 1>&2
   rm -f $MKCONFIG $SCRIPT
   exit 1
@@ -74,7 +75,10 @@ function warning {
 }
 
 function warn_writable {
-  [ -n "$sudo" -o -w "$2" ] || warning "cannot write $1=$2"
+  case $# in
+    2) [ -n "$sudo" -o -w "$2" ] || warning "cannot write $1=$2" ;;
+    *) fail "Fault in `basename $0`; warn_writable got $# arguments" ;;
+  esac
 }
 
 function looking-for {
@@ -252,11 +256,11 @@ log LUA_INSTALL_LMOD="$LUA_INSTALL_LMOD"
 ################################################################
 
 if [ -r mk.config ]; then
-  INCLUDE_MK_CONFIG='<mk.config'
+  INCLUDE_MK_CONFIG=yes
   sed 's/ *= */=/' mk.config > $SCRIPT
   . $SCRIPT
 else
-  INCLUDE_MK_CONFIG=''
+  INCLUDE_MK_CONFIG=
   sed 's/ *= */=/' mk.config.defaults | 
   grep -v LUA_INSTALL | grep -vw BINDIR > $SCRIPT
   . $SCRIPT
@@ -295,8 +299,15 @@ if [ -z "$BINDIR" ]; then
   IFS="$xxx"
 fi
 
+[ -z "$BINDIR" ] && 
+fail 'The configure script could not find a suitable installation directory.
+Please edit a mk.config file and run configure again, or else try
+  ./configure --sudo
+  make
+  sudo make install'
+
 [ -d "$BINDIR" ] || fail "BINDIR=$BINDIR is not a directory"
-[ -w "$BINDIR" ] || warning "cannot write BINDIR=$BINDIR"
+warn_writable BINDIR "$BINDIR"
 
 log "BINDIR=$BINDIR"
 
@@ -388,7 +399,7 @@ if [ -z "$LOCK_METHOD" ]; then
     LOCKLIBS=
   fi
 
-  FCNTL="/usr/include/fcntl.h /usr/include/sys/fcntl.h"
+  FCNTL="/usr/include/fcntl.h /usr/include/*/fcntl.h"
   if [ -z "$LOCK_METHOD" ] && grep -w F_SETLK $FCNTL >/dev/null 2>/dev/null; then
     LOCK_METHOD=FCNTL
   fi
@@ -451,15 +462,18 @@ cat <<'EOF' > $MKCONFIG
 #
 EOF
 
-echo "$INCLUDE_MK_CONFIG" >> $MKCONFIG
 if [ -z "$INCLUDE_MK_CONFIG" ]; then
 
-cat >> $MKCONFIG <<EOF
+cat > $MKCONFIG <<EOF
 MOD_NAME         = $MOD_NAME
 BIN_NAME         = $BIN_NAME
 BINDIR           = $BINDIR
 MOD_VERSION      = 3.0.0
 EOF
+
+else
+
+  sed 's/[ 	]*#.*//' mk.config > $MKCONFIG
 
 fi
 
