refactor configure script to make searches more explicit

diff --git a/handbuild/configure b/handbuild/configure
--- a/handbuild/configure
+++ b/handbuild/configure
@@ -1,5 +1,41 @@
 #!/bin/bash
 
+function usage {
+  cat <<EOF 1>&2
+Usage: `basename $0` [--help] [--sudo]
+
+Options:
+    --help   # this help message
+    --sudo   # will install with sudo; assume write permissions
+EOF
+  exit 0
+}
+
+sudo=
+
+case $1 in
+   --help|-help) usage ;;
+   --sudo|-sudo) sudo=true ; shift ;;
+   -*) usage ;;
+   ?) usage ;;
+esac
+
+
+################################################################
+# 
+# places to search for things
+
+
+LIBSEARCH="/usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64"
+CCSEARCH="gcc cc"
+LUANAMESEARCH="lua5.1 lua"
+INCSEARCH="/usr/include /usr/include/lua5.1 /usr/local/include /usr/local/include/lua5.1 /usr/local/lua/include /usr/local/include/lua /usr/include/lua /usr/local/gnu/include"
+
+
+
+
+################################################################
+
 TEMPFILE="`which tempfile 2>/dev/null`"
 
 if [ -x "$TEMPFILE" ]; then
@@ -63,14 +99,12 @@ function has_lib {
 
 ################################################################
 
-COMPILERS="gcc cc"
-
-for CC in $COMPILERS
+for CC in $CCSEARCH
 do
   [ -x "`which $CC 2>/dev/null`" ] && break
 done
 [ -x "`which $CC 2>/dev/null`" ] || 
-  fail "Cannot find executable C compiler (tried $COMPILERS)"
+  fail "Cannot find executable C compiler (tried $CCSEARCH)"
 
 log "CC=$CC"
 
@@ -94,7 +128,7 @@ esac
 if [ ! -x "$LUABIN" ]
 then
   # N.B. which's exit code is very broken on solaris
-  for bin in lua5.1 lua; do
+  for bin in $LUANAMESEARCH; do
       if which $bin >/dev/null 2>&1; then
         LUABIN="`which $bin`"
         if [ -n "$LUABIN" -a -x "$LUABIN" ]; then
@@ -182,7 +216,7 @@ show('LUA_INSTALL_CMOD', cmod)
 show('LUA_INSTALL_LMOD', lmod)
 EOF
 
-eval `$LUABIN $SCRIPT $$ || { cat -n $SCRIPT 1>&2; }`
+eval `$LUABIN $SCRIPT "$sudo" || { cat -n $SCRIPT 1>&2; }`
 log DLEXT=$DLEXT
 log LUA_INSTALL_CMOD="$LUA_INSTALL_CMOD"
 log LUA_INSTALL_LMOD="$LUA_INSTALL_LMOD"
@@ -202,18 +236,28 @@ fi
 
 [ -d "$LUA_INSTALL_CMOD" ] || 
    fail "LUA_INSTALL_CMOD=$LUA_INSTALL_CMOD is not a directory"
-[ -w "$LUA_INSTALL_CMOD" ] ||
-   warning "cannot write LUA_INSTALL_CMOD=$LUA_INSTALL_CMOD"
+warn_writable LUA_INSTALL_CMOD "$LUA_INSTALL_CMOD"
 
 [ -d "$LUA_INSTALL_LMOD" ] ||
    fail "LUA_INSTALL_LMOD=$LUA_INSTALL_LMOD is not a directory"
-[ -w "$LUA_INSTALL_LMOD" ] ||
-   warning "cannot write LUA_INSTALL_LMOD=$LUA_INSTALL_LMOD"
+warn_writable LUA_INSTALL_LMOD "$LUA_INSTALL_LMOD"
 
 if [ -z "$BINDIR" ]; then
   for dir in /usr/local/bin /usr/unsup/nr/bin $HOME/bin; do
-    [ -d "$dir" -a -w "$dir" ] && { BINDIR="$dir"; break; }
+    [ -d "$dir" -a '(' -n "$sudo" -o -w "$dir" ")" ] && { BINDIR="$dir"; break; }
   done
+fi
+
+if [ -z "$BINDIR" ]; then
+  xxx="$IFS"
+  IFS=":"
+  for dir in $PATH; do
+    case $dir in
+      /*) [ -d "$dir" -a '(' -n "$sudo" -o -w "$dir" ")" ] && { BINDIR="$dir"; break; }
+          ;;
+    esac
+  done
+  IFS="$xxx"
 fi
 
 [ -d "$BINDIR" ] || fail "BINDIR=$BINDIR is not a directory"
@@ -223,14 +267,13 @@ log "BINDIR=$BINDIR"
 
 ################################################################
 #
-# places to look for lua header files
+# find CFLAGS to pick up lua header files
 
-INCDIRS="/usr/include /usr/include/lua5.1 /usr/local/include /usr/local/include/lua5.1 /usr/local/lua/include /usr/local/include/lua /usr/include/lua /usr/local/gnu/include"
 
 if pkg-config --cflags lua5.1 > /dev/null 2>/dev/null; then
   LUA_CFLAGS=`pkg-config --cflags lua5.1`
 else
-  for dir in $INCDIRS; do
+  for dir in $INCSEARCH; do
     if [ -r $dir/lua.h -a -r $dir/lauxlib.h ] &&
        grep 'LUA_VERSION.*5\.1' $dir/lua.h > /dev/null
     then
@@ -270,7 +313,7 @@ if pkg-config --libs lua5.1 > /dev/null 2>/dev/null; then
   LUA_LFLAGS=`pkg-config --libs lua5.1`
 else
   if [ -z "$LUALIBDIR" ]; then
-    for LUALIBNAME in lua lua5.1; do
+    for LUALIBNAME in $LUANAMESEARCH; do
       if has_lib $LUALIBNAME; then
         LUALIBDIR=`lib_dir $LUALIBNAME`
         break
@@ -291,7 +334,7 @@ log "LUA_LFLAGS=$LUA_LFLAGS"
 if [ -z "$LOCK_METHOD" ]; then
   if [ -r /usr/include/lockfile.h ] && has_lib lockfile; then
     LOCK_METHOD=LOCKFILE
-    LOCKLIBS="-L `lib_dir lockfile` -llockfile"
+    LOCKLIBS="-L`lib_dir lockfile` -llockfile"
   else
     LOCKLIBS=
   fi
